### ISSUE TITLE
Support for mutually exclusive features

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-hack#229] opened 2024-02-02 05:19 UTC
Essentially the opposite of `--group-features`. My intended use case is supporting wasm-bindgen and quickcheck, the latter of which cannot compile to `wasm32-unknown-unknown`. Perhaps more common would be supporting multiple async runtimes, which can naturally not be enabled together.

**Comment by taiki-e** [comment] 2024-02-02 05:23
Duplicate of #132

**Closed by taiki-e** 2024-02-02 05:23 UTC

**Comment by jhpratt** [comment] 2024-02-02 05:25
Thanks for the quick response! I should have known to search. Are you still open to adding a flag? I can look into adding it myself if so.

**Comment by taiki-e** [comment] 2024-02-02 05:31
> Are you still open to adding a flag?

Yes, I would accept a PR to add a flag for this.
